name: Volunteer for presentation
description: I'd like to present my solutions and discuss with the course!
title: I'd like to present my solutions and discuss with the course!
labels: ['volunteer for presentation']
body:
  - type: input
    id: repository
    attributes:
      label: Repository
      description: Paste a link to your GitHub repository.
    validations:
      required: true
  - type: checkboxes
    id: confirmation_of_accessibility
    attributes:
      label: Access rights
      description: Please confirm that your GitHub repository is public, or you have [granted access](https://docs.github.com/de/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) to the [course supervisors](https://github.com/BMCV/mobi-fs3-python/blob/master/SUPERVISORS.md).
      options:
        - label: I hereby confirm that the supervisors can access my GitHub repository.
          required: true
  - type: checkboxes
    id: confirmation_of_having_pushed
    attributes:
      label: Git commit and push
      description: Please confirm that you have pushed the work which is relevant to this issue to your GitHub repository.
      options:
        - label: I hereby confirm that I have committed and pushed to my GitHub repository.
          required: true
  - type: dropdown
    id: labsession
    attributes:
      label: Lab session
      description: The lab session for which you volunteer to present your solution.
      options:
        - Introduction (Cheat Sheet)
        - Lab Session 1
        - Lab Session 2
        - Lab Session 3
        - Lab Session 4
        - Bonus Tasks
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional context for the comments
      description: Give some context, if applicable.
    validations:
      required: false